#ifndef UNTITLED4_DEFINES_H
#define UNTITLED4_DEFINES_H

#define MAX_USERS 20
#define MAX_FRIENDS 10
#define MAX_REQUESTS 10
#define LINEA_ASTERISCOS "******************************"
#define LINEA_GUION "---------------"
#define FALSE 0
#define TRUE 1
#define MAX_WORD_LENGHT 20
#define MAX_PUBLICATIONS 10
#define MAX_TEXT_LENGTH 120

#define MAX_ID_NAME_LENGHT 20
#define MAX_NAME_LENGHT 20
#define MAX_PASSWORD_LENGHT 20
#define MAX_CORREO_LENGHT 30
#define MAX_CITY_LENGHT 20
#define MAX_WORD_LENGHT 20
#define MAX_GUSTOS 10
#define GUSTOS_LENGTH 20

#endif //UNTITLED4_DEFINES_H
